name: hollow_country_provider
description: The plugin provides several methods to fetch countries info, Apply filter, and perform search operations.
version: 1.0.0
homepage: https://github.com/jluukka-ge/country_provider

environment:
  sdk: '>=2.12.0'

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
